version: '3.8'

services:
  postgres:
    container_name: nest-auth-users
    image: postgres:16.10-alpine3.21
    ports:
     - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: docker-db
      PGDATA: /data/postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./data/pg:/data/postgres